### ISSUE TITLE
无法检测名称带下划线的玩家的变量

### ISSUE THREAD

**Issue by Clexus** [handy-git/OfflinePapi#1]
如题

**Comment by handy-git** [comment]
> 如题

确实存在这个问题，我想想怎么优化下

**Comment by Clexus** [comment]
> > 如题
> 
> 确实存在这个问题，我想想怎么优化下

参考一下parseother扩展的检测方式

**Comment by handy-git** [comment]
> > > 如题
> > 
> > 
> > 确实存在这个问题，我想想怎么优化下
> 
> 参考一下parseother扩展的检测方式

有想法可以pr贡献代码,我比较忙,下周才会想办法

**Comment by Clexus** [comment]
> > > > 如题
> > > 
> > > 
> > > 确实存在这个问题，我想想怎么优化下
> > 
> > 
> > 参考一下parseother扩展的检测方式
> 
> 有想法可以pr贡献代码,我比较忙,下周才会想办法

```java

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {
    public static void main(String[] args) {
        String input = "%player_{ash}_{player_name}%";
        String patternString = "%[^{]*?\\{([^}]+)}%";

        Pattern pattern = Pattern.compile(patternString);
        Matcher matcher = pattern.matcher(input);

        while (matcher.find()) {
            String match = matcher.group(1);
            System.out.println(match);
        }
    }
}

``` 
我做了一段正则表达式的事例代码，你可以参考一下

**Comment by handy-git** [comment]
> > > > > 如题
> > > > 
> > > > 
> > > > 确实存在这个问题，我想想怎么优化下
> > > 
> > > 
> > > 参考一下parseother扩展的检测方式
> > 
> > 
> > 有想法可以pr贡献代码,我比较忙,下周才会想办法
> 
> ```java
> import java.util.regex.Matcher;
> import java.util.regex.Pattern;
> 
> public class Main {
>     public static void main(String[] args) {
>         String input = "%player_{ash}_{player_name}%";
>         String patternString = "%[^{]*?\\{([^}]+)}%";
> 
>         Pattern pattern = Pattern.compile(patternString);
>         Matcher matcher = pattern.matcher(input);
> 
>         while (matcher.find()) {
>             String match = matcher.group(1);
>             System.out.println(match);
>         }
>     }
> }
> ```
> 
> 我做了一段正则表达式的事例代码，你可以参考一下，这个输入会输出ash 和 player_name

很感谢的你关注和代码
1. 你这个正则我复制测试跑不通
2. 我并不想改变现在的变量格式，会导致已经使用的出现很多问题的
3. 我在1.0.6已经修复了，你可以在releases中下载1.0.6版本进行测试了
