### ISSUE TITLE
获取不到变量数据不返回null，且望加入自定义返回数据。

### ISSUE THREAD

**Issue by CloudGFX** [handy-git/OfflinePapi#2]
**主要问题**：原本如果获取不到变量数据直接返回null，不会返回null而是变量名%offlinepapi_xxx%本身。
**可新增功能**：添加自定义配置项，如果数据库没有该数据或该数据异常就返回配置文件中设定的值或替代变量。

**Comment by handy-git** [comment]
现在获取不到返回的就是null

**Comment by CloudGFX** [comment]
**最新版本1.0.8**
至少我在**服务端(1.12.2 Catserver)**上表现为获取不到就返回变量名本身了。
**情况如下：**
某名玩家有一段时间未上线，对其各种offline变量解析会出现如上情况，是不是过期数据被清除了？
另外感觉允许自定义返回值的功能还不错。

**Comment by handy-git** [comment]
返回变量本身那大概率你变量写错了

**Comment by CloudGFX** [comment]
不可能啊，因为本身之前就是能正常解析，当玩家一段时间未上线再去解析就出现了这个情况。

**Comment by handy-git** [comment]
> 不可能啊，因为本身之前就是能正常解析，当玩家一段时间未上线再去解析就出现了这个情况。

请提供下你的 原变量 和你 输入的本插件变量 %offlinepapi_%

**Comment by CloudGFX** [comment]
Global Market Plus插件、EpicPokeUnion插件下都有这种情况，例如%EpicPokeUnion_Union% -> %offlinepapi_me_EpicPokeUnion_Union%会出现这种情况，其他插件变量没用到。

**Comment by handy-git** [comment]
> Global Market Plus插件、EpicPokeUnion插件下都有这种情况，例如%EpicPokeUnion_Union% -> %offlinepapi_me_EpicPokeUnion_Union%会出现这种情况，其他插件变量没用到。

 你可以使用指令查询下 /papi parse me %offlinepapi_me_EpicPokeUnion_Union% 返回什么

**Comment by CloudGFX** [comment]
正常能返回自己的union名，但是问题在于如果parse的玩家长时间未上线，则parse出来返回null（变量名本身），而因为原变量无法对离线玩家解析，所以用offlinepapi解析，但offlinepapi对于长时间未上线玩家返回是null。我也没头绪，不知道什么原因，如果实在难解决就算了。谢谢。

**Comment by handy-git** [comment]
> 正常能返回自己的union名，但是问题在于如果parse的玩家长时间未上线，则parse出来返回null（变量名本身），而因为原变量无法对离线玩家解析，所以用offlinepapi解析，但offlinepapi对于长时间未上线玩家返回是null。我也没头绪，不知道什么原因，如果实在难解决就算了。谢谢。

1.1.0 做好了，添加了自定义返回数据，你qq私信我下，我发你

**Comment by CloudGFX** [comment]
好的
